name: Build

on: [push, pull_request]

jobs:
  param:
    name: Determine parameter
    runs-on: ubuntu-24.04
    steps:
      - id: param
        run: |
          python3 <<EOF >"$GITHUB_OUTPUT"
          import json
          if '${{ github.ref_type }}' == 'tag':
            branch = ['${{ github.ref_name }}'.split('.')[0]]
            release = True
          else:
            branch = ['2026', '2025']
            release = False
          print(f"branch={json.dumps(branch)}")
          print(f"release={json.dumps(release)}")
          EOF
    outputs:
      branch: ${{ steps.param.outputs.branch }}

  download_source:
    name: Download source
    runs-on: ubuntu-24.04
    needs: param
    strategy:
      fail-fast: true
      matrix:
        branch: ${{ fromJson(needs.param.outputs.branch) }}
    steps:
      - uses: actions/checkout@v4

      - name: Download source
        run: |
          ./main.py --branch ${{ matrix.branch }} --profile 64-ucrt --mingw-lite-version 15.2.0-r0 --download-only

      - uses: actions/upload-artifact@v4
        with:
          name: src-${{ matrix.branch }}
          path: |
            assets

  build_container:
    name: Build container
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Build container
        run: |
          podman build -t mingw-lite/buildenv support/buildenv

          mkdir assets
          podman save mingw-lite/buildenv:latest | zstd -o assets/buildenv.tar.zst

      - name: Upload container
        uses: actions/upload-artifact@v4
        with:
          name: buildenv
          path: assets/buildenv.tar.zst

  build:
    name: Build
    needs: [param, download_source, build_container]
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJson(needs.param.outputs.branch) }}
        profile: [
          64-mcf, 64-win32, 64-ucrt, 64-msvcrt,
          32-mcf, 32-win32, 32-ucrt, 32-msvcrt,

          # profile variants for micro architectures
          64_v2-mcf, 64_v2-win32, 64_v2-ucrt, 64_v2-msvcrt,
        ]
        mingw_lite_branch: [15, 14, 13]
        include:
          - mingw_lite_branch: 15
            mingw_lite_version: 15.2.0-r0
          - mingw_lite_branch: 14
            mingw_lite_version: 14.3.0-r0
          - mingw_lite_branch: 13
            mingw_lite_version: 13.4.0-r0
    uses: ./.github/workflows/build_single.yml
    with:
      branch: ${{ matrix.branch }}
      profile: ${{ matrix.profile }}
      mingw_lite_branch: ${{ matrix.mingw_lite_branch }}
      mingw_lite_version: ${{ matrix.mingw_lite_version }}
